apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: team24-backend
  name: team24-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team24-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: team24-backend
    spec:
      containers:
      - image: trirong/team24-backend:v0.2
        imagePullPolicy: IfNotPresent
        name: team24-backend
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
