apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: team24-client
  name: team24-client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team24-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: team24-client
    spec:
      containers:
      - image: trirong/team24-client:v0.2
        imagePullPolicy: IfNotPresent
        name: team24-client
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
