apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "1396"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  sessionAffinity: None
  type: ClusterIP
