apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-24T11:55:34Z"
  labels:
    app: backend
  name: backend
  namespace: default
  resourceVersion: "2746"
  selfLink: /api/v1/namespaces/default/services/backend
  uid: 79a17c45-9db5-11ea-879e-0242a96a2e4c
spec:
  clusterIP: 10.110.197.246
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31945
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.202
