apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-24T08:12:30Z"
  generation: 1
  labels:
    app: client
  name: client
  namespace: default
  resourceVersion: "1360"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/client
  uid: 5060cdeb-9d96-11ea-9ac9-0242a5cde95d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
    spec:
      containers:
      - image: trirong/client:v0.1
        imagePullPolicy: IfNotPresent
        name: client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-24T08:12:32Z"
    lastUpdateTime: "2020-05-24T08:12:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-24T08:12:30Z"
    lastUpdateTime: "2020-05-24T08:12:32Z"
    message: ReplicaSet "client-6dc6646c86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
